### ISSUE TITLE
Could not deserialize crafting tree sent by the server.

### ISSUE THREAD

**Issue by Might-dev** [GTNewHorizons/Applied-Energistics-2-Unofficial#499]
[00:30:11] [Client thread/INFO]: [com.glodblock.github.coremod.FCClassTransformer:transform:32]: [AE2FC] Transforming class: appeng.client.gui.widgets.GuiCraftingTree
[00:30:11] [Client thread/ERROR]: Could not deserialize crafting tree sent by the server.
java.lang.ClassCastException: appeng.crafting.v2.resolvers.CraftableItemResolver$RequestAndPerCraftAmount cannot be cast to appeng.crafting.v2.CraftingRequest
	at appeng.crafting.v2.CraftingRequest$UsedResolverEntry.<init>(CraftingRequest.java:60) ~[CraftingRequest$UsedResolverEntry.class:?]
	at appeng.crafting.v2.CraftingTreeSerializer.readSerializableAndQueueChildren(CraftingTreeSerializer.java:161) ~[CraftingTreeSerializer.class:?]
	at appeng.crafting.v2.CraftingTreeSerializer.lambda$readSerializableAndQueueChildren$1(CraftingTreeSerializer.java:170) ~[CraftingTreeSerializer.class:?]
	at appeng.crafting.v2.CraftingTreeSerializer.doWork(CraftingTreeSerializer.java:316) ~[CraftingTreeSerializer.class:?]
	at appeng.crafting.v2.CraftingJobV2.deserialize(CraftingJobV2.java:100) ~[CraftingJobV2.class:?]
	at appeng.core.sync.packets.PacketCraftingTreeData.onFullClientData(PacketCraftingTreeData.java:142) [PacketCraftingTreeData.class:?]
	at appeng.core.sync.packets.PacketCraftingTreeData.clientPacketData(PacketCraftingTreeData.java:106) [PacketCraftingTreeData.class:?]
	at appeng.core.sync.network.AppEngClientPacketHandler.onPacketData(AppEngClientPacketHandler.java:35) [AppEngClientPacketHandler.class:?]
	at appeng.core.sync.network.NetworkHandler.clientPacket(NetworkHandler.java:85) [NetworkHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1234_NetworkHandler_clientPacket_ClientCustomPacketEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
	at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [netty-all-4.0.10.Final.jar:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [netty-all-4.0.10.Final.jar:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(MinecraftMixin.java:1617) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(MinecraftMixin.java:988) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:4005) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:133) [launchwrapper-1.12.jar:?]

**Comment by Kogepan229** [comment]
Since the AE2FC's Transfthomer has been removed, this problem should no longer occur now.

> I sometimes get the same issue, though I think it's a different root cause

Fixed in https://github.com/GTNewHorizons/ThaumicEnergistics/pull/97
