### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/Applied-Energistics-2-Unofficial#604]
[14:11:14] [Server thread/ERROR] [FML]: A TileEntity BlockCableBus(appeng.parts.layers.LayerIEnergyHandler_TileCableBus) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
        at appeng.tile.events.AETileEventHandler.readFromNBT(AETileEventHandler.java:54) ~[AETileEventHandler.class:?]
        at appeng.tile.AEBaseTile.func_145839_a(AEBaseTile.java:121) ~[AEBaseTile.class:?]
        at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:132) [aor.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:526) [aqk.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:43) [ChunkIOProvider.class:1.7.10-staging-eccfcc87]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:14) [ChunkIOProvider.class:1.7.10-staging-eccfcc87]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:1.7.10-staging-eccfcc87]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:1.7.10-staging-eccfcc87]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:1.7.10-staging-eccfcc87]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:198) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:171) [ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:309) [ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:780) [ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:683) [ahb.class:?]
        at net.minecraft.world.World.func_72878_l(World.java:4203) [ahb.class:?]
        at net.minecraft.world.World.func_72864_z(World.java:4209) [ahb.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.updatePower(TileEntityBasicBlock.java:282) [TileEntityBasicBlock.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.onNeighborChange(TileEntityBasicBlock.java:276) [TileEntityBasicBlock.class:?]
        at mekanism.common.block.BlockMachine.func_149695_a(BlockMachine.java:956) [BlockMachine.class:?]
        at net.minecraft.world.World.func_147460_e(World.java:1128) [ahb.class:?]
        at aroma1997.uncomplication.enet.EnergyNetLocal.update(EnergyNetLocal.java:616) [EnergyNetLocal.class:2.5.21]
        at aroma1997.uncomplication.enet.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:95) [EnergyNetLocal.class:2.5.21]
        at aroma1997.uncomplication.enet.EnergyNetLocal.removeTile(EnergyNetLocal.java:85) [EnergyNetLocal.class:2.5.21]
        at aroma1997.uncomplication.enet.EventHandler.onEnergyTileUnload(EventHandler.java:37) [EventHandler.class:2.5.21]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_715_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic) [?:1.7.10-staging-eccfcc87]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-staging-eccfcc87]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:149) [EventBus.class:1.7.10-staging-eccfcc87]
        at ic2.core.block.machine.tileentity.TileEntityElectricMachine.onUnloaded(TileEntityElectricMachine.java:90) [TileEntityElectricMachine.class:?]
        at com.denfop.tiles.base.TileEntityMultiMachine.onUnloaded(TileEntityMultiMachine.java:165) [TileEntityMultiMachine.class:2.5.21]
        at ic2.core.block.TileEntityBlock.onChunkUnload(TileEntityBlock.java:78) [TileEntityBlock.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2516) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at appeng.tile.events.AETileEventHandler.readFromNBT(AETileEventHandler.java:52) ~[AETileEventHandler.class:?]
        ... 36 more
Caused by: java.lang.IllegalStateException: Invalid Crafting Link for Object
        at appeng.crafting.CraftingLink.<init>(CraftingLink.java:38) ~[CraftingLink.class:?]
        at appeng.core.api.ApiStorage.loadCraftingLink(ApiStorage.java:41) ~[ApiStorage.class:?]
        at appeng.helpers.MultiCraftingTracker.readFromNBT(MultiCraftingTracker.java:49) ~[MultiCraftingTracker.class:?]
        at appeng.parts.automation.PartExportBus.readFromNBT(PartExportBus.java:80) ~[PartExportBus.class:?]
        at appeng.parts.CableBusContainer.readFromNBT(CableBusContainer.java:878) ~[CableBusContainer.class:?]
        at appeng.tile.networking.TileCableBus.readFromNBT_TileCableBus(TileCableBus.java:61) ~[TileCableBus.class:?]
        at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
        at appeng.tile.events.AETileEventHandler.readFromNBT(AETileEventHandler.java:52) ~[AETileEventHandler.class:?]
        ... 36 more

**Comment by lc-1337** [comment]
Need confirm that is happens in dailly, can happens with level emitter/export bus with crafting card. mb with dual interface.
